name:                hs-pcap
version:             0.1.0.0
github:              "lgarithm/hs-pcap"
license:             BSD3
author:              "lgarithm"
maintainer:          "lgarithm@gmail.com"
copyright:           "2020 lgarithm"

extra-source-files: []
# - README.md
# - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/lgarithm/hs-pcap#README.md>

dependencies:
- base >= 4.7 && < 5
- base-compat
- bytestring
- HUnit
- parsec
- split
- template-haskell
- utf8-string

library:
  source-dirs: src

executables:
  pcap-read:
    main:                pcap-read.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hs-pcap

tests:
  hs-pcap-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hs-example
